# Generated by Django 4.0.2 on 2022-02-13 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0003_intro_content_en_intro_content_es_intro_content_fr_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='intro',
            name='content_en',
        ),
        migrations.RemoveField(
            model_name='intro',
            name='content_es',
        ),
        migrations.RemoveField(
            model_name='intro',
            name='content_fr',
        ),
        migrations.RemoveField(
            model_name='intro',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='intro',
            name='title_es',
        ),
        migrations.RemoveField(
            model_name='intro',
            name='title_fr',
        ),
    ]
