# Generated by Django 4.0.2 on 2022-02-13 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0004_remove_intro_content_en_remove_intro_content_es_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutus',
            options={'verbose_name_plural': 'about us'},
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name_plural': 'contact'},
        ),
        migrations.AlterModelOptions(
            name='intro',
            options={'verbose_name_plural': 'intro'},
        ),
        migrations.AlterModelOptions(
            name='people',
            options={'verbose_name_plural': 'peoples'},
        ),
        migrations.AlterModelOptions(
            name='whatwedo',
            options={'verbose_name_plural': 'what we do (s)'},
        ),
        migrations.AddField(
            model_name='contact',
            name='address_link',
            field=models.CharField(default='https://goo.gl/maps/Sic5Z5itEz2HfNGS7', max_length=500),
            preserve_default=False,
        ),
    ]
